Package.describe({
  name: "reactioncommerce:core-theme",
  summary: "Reaction Commerce base theme",
  version: "1.3.1",
  git: "https://github.com/reactioncommerce/core-theme.git"
});

Package.onUse(function(api) {
  api.versionsFrom('METEOR@1.0');
  api.addFiles('theme-data.js', 'server');
  api.export(['ThemeData']);

  // Everything after this point is generated by the build-package.sh
  // AUTOGENERATED
  api.addFiles([
    'default/bootstrap.rtl.less',
    'default/mixins.less',
    'default/variables.less',
    'theme/accounts/accounts.less',
    'theme/accounts/inline/inline.less',
    'theme/cart/cart.less',
    'theme/cart/cartDrawer/cartDrawer.less',
    'theme/cart/cartDrawer/cartItems/cartItems.less',
    'theme/cart/cartDrawer/cartSubTotals/cartSubTotals.less',
    'theme/cart/cartIcon/cartIcon.less',
    'theme/cart/checkout/addressBook/addressBook.less',
    'theme/cart/checkout/checkout.less',
    'theme/cart/checkout/completed/completed.less',
    'theme/cart/checkout/header/header.less',
    'theme/cart/checkout/login/login.less',
    'theme/cart/checkout/payment/methods/cards.less',
    'theme/cart/checkout/payment/payment.less',
    'theme/cart/checkout/progressBar/progressBar.less',
    'theme/cart/checkout/review/review.less',
    'theme/cart/checkout/shipping/shipping.less',
    'theme/dashboard/console/console.less',
    'theme/dashboard/dashboard.less',
    'theme/dashboard/orders/details/detail.less',
    'theme/dashboard/orders/orders.less',
    'theme/dashboard/orders/social/orderSocial.less',
    'theme/dashboard/orders/stateHelpers/completed/completed.less',
    'theme/dashboard/orders/stateHelpers/documents/documents.less',
    'theme/dashboard/orders/stateHelpers/packing/packing.less',
    'theme/dashboard/orders/stateHelpers/payment/payment.less',
    'theme/dashboard/orders/stateHelpers/shipped/shipped.less',
    'theme/dashboard/orders/stateHelpers/tracking/tracking.less',
    'theme/dashboard/packages/grid/grid.less',
    'theme/dashboard/packages/grid/package/package.less',
    'theme/dashboard/packages/packages.less',
    'theme/dashboard/shop/accounts.less',
    'theme/dashboard/shop/settings.less',
    'theme/dashboard/widget/widget.less',
    'theme/layout/footer/footer.less',
    'theme/layout/header/header.less',
    'theme/layout/header/tags/tags.less',
    'theme/layout/layout.less',
    'theme/products/productDetail/attributes/attributes.less',
    'theme/products/productDetail/images/productImageGallery.less',
    'theme/products/productDetail/productDetail.less',
    'theme/products/productDetail/social/social.less',
    'theme/products/productDetail/tags/tags.less',
    'theme/products/productDetail/variants/variant.less',
    'theme/products/productDetail/variants/variantForm/childVariant/childVariant.less',
    'theme/products/productDetail/variants/variantForm/variantForm.less',
    'theme/products/productDetail/variants/variantList/variantList.less',
    'theme/products/productGrid/productGrid.less',
    'theme/products/productList/productList.less',
    'theme/products/products.less',
  ], 'server', {isAsset:true});
});
